# see https://github.com/bobvanderlinden/probot-auto-merge
updateBranch: true
reportStatus: true
blockingTitleRegex: '\bWIP\b'
deleteBranchAfterMerge: true
rules:
- minApprovals:
    CONTRIBUTOR: 1
- requiredLabels:
    - merge
