version: 2.1

# --- Anchor alias ---- #
# - Docker configuration - #
alias:
# https://circleci.com/docs/2.0/circleci-images/#nodejs
  - &docker_node14_configuration
    docker:
      - image: circleci/node:14.13.1
        user: root
# - Jobs filters - #
  - &filters_allow_tags
    tags:
      only: /^v.*/
  - &filters_ignore_branches
    branches:
      ignore: /.*/
  - &filters_ignore_tags
    tags:
      ignore: /.*/
# - Step - #
  - &preconfig-github-pkg
    run:
      name: Preconfigure environment ~/.npmrc
      command: |
        echo "@habx:registry=https://npm.pkg.github.com/" > ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
  - &preconfig-npmjs
    run:
      name: Preconfigure environment ~/.npmrc
      command: |
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
# - Node modules - #
  - &install_node_modules_with_cache
    node/with-cache:
        dir: node_modules
        cache-version: dev{{ .Environment.CACHE_VERSION }}
        steps:
          - run:
              name: Install node module
              command: npm install
  - &install_node_modules_with_cache_production
    node/with-cache:
      dir: node_modules
      cache-version: prod{{ .Environment.CACHE_VERSION }}
      steps:
        - run:
            name: Install node module production
            command: npm install --production
  - &fetch_node_modules_with_cache_production
    node/with-cache:
      dir: node_modules
      cache-version: prod{{ .Environment.CACHE_VERSION }}
      steps:
        - run: echo
jobs:
  build:
    <<: *docker_node14_configuration
    steps:
      - checkout
      - *install_node_modules_with_cache_production
      - *install_node_modules_with_cache
      - run: export NODE_ENV=production; npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist

  storybook-build:
    <<: *docker_node14_configuration
    steps:
      - checkout
      - *install_node_modules_with_cache
      - attach_workspace:
          at: ~/project
      - *install_node_modules_with_cache
      - run: npm run storybook:build

  lint:
    <<: *docker_node14_configuration
    steps:
      - checkout
      - *install_node_modules_with_cache
      - run: npm run lint

  tests:
    <<: *docker_node14_configuration
    steps:
      - checkout
      - *install_node_modules_with_cache
      - run: npm run test

  github-pkg-publish:
    <<: *docker_node14_configuration
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - *preconfig-github-pkg
      - *install_node_modules_with_cache
      - run: rm .npmrc || echo ".npmrc not found"
      - run: npm publish

  npmjs-publish:
    <<: *docker_node14_configuration
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - *preconfig-npmjs
      - *install_node_modules_with_cache
      - run: jq -M 'del(.publishConfig)' package.json > _package.json; mv _package.json package.json
      - run: npm publish

  storybook-publish:
    <<: *docker_node14_configuration
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - *install_node_modules_with_cache
      - run: npm run storybook:deploy

orbs:
  node: circleci/node@1.0.1
# --- END --- #
# --------------------------------------------------- #
# -------------- DEFINE YOUR WORKFLOW --------------- #
# --------------------------------------------------- #
workflows:
  build:
    jobs:
      - build:
          filters:
            <<: *filters_allow_tags
      - lint:
          filters:
            <<: *filters_allow_tags
      - tests:
          requires:
            - build
            - lint
          filters:
            <<: *filters_allow_tags
      - npmjs-publish:
          context: ts-lib-client-public
          requires:
            - lint
            - build
          filters:
            <<: *filters_allow_tags
            <<: *filters_ignore_branches
      - github-pkg-publish:
          context: ts-lib-client-public
          requires:
            - lint
            - build
          filters:
            <<: *filters_allow_tags
            <<: *filters_ignore_branches
      - storybook-publish:
          context: ts-lib-client-public
          requires:
            - tests
          filters:
            <<: *filters_allow_tags
            <<: *filters_ignore_branches
