# DELETE ME
# This should pretty much disable dependabots (before we completely disable it)
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    allowed_updates:
      - match:
          dependency_name: "doesntexist"

# version: 1
# update_configs:
#   - package_manager: "javascript"
#     directory: "/"
#     update_schedule: "live"
#     version_requirement_updates: "auto"
#     # https://dependabot.com/docs/config-file/#automerged_updates
#     automerged_updates:
#       - match:
#           dependency_type: "development"
#           update_type: "semver:minor"
#       - match:
#           dependency_type: "development"
#           update_type: "in_range"
#       - match:
#           dependency_type: "production"
#           update_type: "semver:patch"
#       - match:
#           dependency_type: "production"
#           update_type: "in_range"
#       - match:
#           dependency_name: "lodash"
#       - match:
#           dependency_name: "@types/*"
#       - match:
#           dependency_name: "@habx/*"
#           update_type: "in_range"
#       - match:
#           dependency_name: "@habx/*"
#           update_type: "semver:minor"
#       - match:
#           dependency_name: "lint-staged"
#       - match:
#           dependency_name: "typescript"
#       - match:
#           dependency_name: "@sentry/*"
#           update_type: "semver:minor"
